/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/educatronica-son.appspot.com/o/threejsEducatronica2.glb?alt=media&token=fd73b978-5740-4fe1-8014-26b0043343cd"
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text035.geometry} material={materials["Material.006"]} />
      <mesh geometry={nodes.Text035_1.geometry} material={materials["Plastico Negro"]} />
      <mesh geometry={nodes.Text035_2.geometry} material={materials["Material.002"]} />
      <mesh geometry={nodes.Text035_3.geometry} material={materials["Material.003"]} />
      <mesh geometry={nodes.Text035_4.geometry} material={materials["Arduino Front"]} />
      <mesh geometry={nodes.Text035_5.geometry} material={materials["Cable Amarillo Trig.002"]} />
      <mesh geometry={nodes.Text035_6.geometry} material={materials["Cable Amarillo Trig.003"]} />
      <mesh geometry={nodes.Text035_7.geometry} material={materials["Cable Amarillo Trig.001"]} />
      <mesh geometry={nodes.Text035_8.geometry} material={materials.Resistencia} />
      <mesh geometry={nodes.Text035_9.geometry} material={materials["Material.001"]} />
      <mesh geometry={nodes.Text035_10.geometry} material={materials["Cable Amarillo Trig.004"]} />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/educatronica-son.appspot.com/o/threejsEducatronica2.glb?alt=media&token=fd73b978-5740-4fe1-8014-26b0043343cd"
);
